auth:
  type: DISABLED
kafka:
  clusters:
    - bootstrapServers: kafka0.vHost:9092,kafka1.vHost:9092,kafka2.vHost:9092
      name: local
      properties: {}
      readOnly: false
rbac:
  roles: []
webclient: {}
