auth:
  type: DISABLED
kafka:
  clusters:
    - bootstrapServers: kafka0.vLocal:9092,kafka1.vLocal:9092,kafka2.vLocal:9092
      name: local
      properties: {}
      readOnly: false
rbac:
  roles: []
webclient: {}
